# Generated by Django 5.1.4 on 2025-01-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default='2024-01-01', unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, default='1000', max_digits=10),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
