# Generated by Django 5.1.4 on 2025-01-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee_email_employee_hire_date_employee_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default='2024-01-01', unique=True),
        ),
    ]
